name: Build Windows Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Configure CMake
      run: |
        cmake -G "Visual Studio 16 2019" -B ${{github.workspace}}/build -T host=x86 -A win32
    
    - name: Build the thing
      run: |
        cd ${{github.workspace}}/build
        cmake --build .  --config Release
  
    - name: Push to Bin
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN  }}
      with:
        source-directory: '${{github.workspace}}/build/Release'
        target-directory: 'windows'
        destination-github-username: 'geode-sdk'
        destination-repository-name: 'bin'
        user-email: hjfodgames@gmail.com
        target-branch: main
