name: Update Bin

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "windows"
          os: windows-latest
          extra_flags: '-G "Visual Studio 16 2019" -T host=x86 -A win32'
          upload_paths:  './build/Release/geode.dll ./build/Release/geode.lib ./build/src/CCZipUtils/Release/CCZipUtils.lib'
          gen_folder: './build/Gen/*'
        - name: "macos"
          os: macos-latest
          extra_flags: ""
          upload_paths:  './build/Geode.dylib ./build/src/CCZipUtils/libCCZipUtils.a ./build/src/addressertest/libAddresserTest.a'
          gen_folder: './build/gen/*'

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
      if: matrix.config.os == 'windows-latest'

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build ${{ matrix.config.extra_flags }} -DGEODE_DONT_BUILD_TEST_MODS=On -DGEODE_BUILD_UNIT_TESTS=On
    
    - name: Build
      run: |
        cd ${{ github.workspace }}/build
        cmake --build . --config Release

    - name: Move files to bin
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        mv ${{ matrix.config.upload_paths }} ./sdk/bin/${{ matrix.config.name }} 
        mv ${{ matrix.config.gen_folder }} ./sdk/bin/${{ matrix.config.name }}/gen
      
    - name: Commit and push to bin
      working-directory: ${{ github.workspace }}/sdk/bin
      run: |
        git checkout main
        git config --global user.email "${{ secrets.GEODE_BOT_EMAIL }}"
        git config --global user.name "GeodeBot"
        git commit -am "Auto-update from https://$GITHUB_SERVER/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
        git push "https://${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}@github.com/geode-sdk/bin.git" main
