name: Build Binaries

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "Windows"
          os: windows-latest
          extra_flags: '-G "Visual Studio 16 2019" -T host=x86 -A win32'
          upload_paths:  |
            ./Gen/Header.hpp
            ./Gen/Interface.hpp
            ./Gen/TempName.hpp
            ./Release/geode.dll
            ./Release/geode.lib
            ./src/CCZipUtils/Release/CCZipUtils.lib
        - name: "macOS"
          os: macos-latest
          extra_flags: ""
          upload_paths:  |
            ./gen/Header.hpp
            ./gen/Interface.hpp
            ./gen/TempName.hpp
            ./Geode.dylib
            ./src/CCZipUtils/libCCZipUtils.a

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
      if: matrix.config.os == 'windows-latest'

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build ${{ matrix.config.extra_flags }} -DGEODE_DONT_BUILD_TEST_MODS=On
    
    - name: Build
      run: |
        cd ${{ github.workspace }}/build
        cmake --build . --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.name }} Loader Binary + Libraries
        path: ${{ matrix.config.upload_paths }}
