name: Build Binaries

on:
  push:
    branches: [ main, addresser ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "Windows"
          os: windows-latest
          extra_flags: '-G "Visual Studio 16 2019" -T host=x86 -A win32'
          gen_paths:  './build/Gen/Header.hpp ./build/Gen/Interface.hpp ./build/Gen/TempName.hpp'
          out_paths: './build/Release/geode.dll ./build/Release/geode.lib ./build/src/inject/windows/Release/XInput9_1_0.dll ./build/src/CCZipUtils/Release/CCZipUtils.lib'
        - name: "macOS"
          os: macos-latest
          extra_flags: ""
          gen_paths:  './build/gen/Header.hpp ./build/gen/Interface.hpp ./build/gen/TempName.hpp'
          out_paths: './build/Geode.dylib ./build/src/CCZipUtils/libCCZipUtils.a'
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
      if: matrix.config.os == 'windows-latest'
    
    - name: Setup env
      run: |
        echo "BUILDCACHE_DIR=${{ github.workspace }}/cache" >> $GITHUB_ENV

    - uses: mikehardy/buildcache-action@v1
      with:
        cache_key: ${{ matrix.config.os }}
        
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build ${{ matrix.config.extra_flags }} -DGEODE_DONT_BUILD_TEST_MODS=On -DGEODE_BUILD_UNIT_TESTS=On
          
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
          
    - name: Move to output folder
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        mkdir ./out
        mkdir ./out/gen
        mv ${{ matrix.config.out_paths }} ./out
        mv ${{ matrix.config.gen_paths }} ./out/gen
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.name }} Loader Binary + Libraries
        path: ./out/
