name: Build Windows Binaries

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-latest,
            extra_flags: '-G "Visual Studio 16 2019" -T host=x86 -A win32",
          }
        - {
            name: "macOS",
            os: macos-latest,
            extra_flags: ""
          }

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
      if: matrix.config.os == 'windows-latest'

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build ${{matrix.config.extra_args}} -DGEODE_DONT_BUILD_TEST_MODS=On
    
    - name: Build
      run: |
        cd ${{github.workspace}}/build
        cmake --build . --config Release

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: Windows Loader Binary + Libraries
        path: |
          ${{github.workspace}}/build/Gen/Header.hpp
          ${{github.workspace}}/build/Gen/Interface.hpp
          ${{github.workspace}}/build/Gen/TempName.hpp
          ${{github.workspace}}/build/Release/geode.dll
          ${{github.workspace}}/build/Release/geode.lib
          ${{github.workspace}}/build/src/CCZipUtils/Release/CCZipUtils.lib
      # TODO: idk where it is on mac
      if: matrix.config.os == 'window-latest'
