name: Update Suite

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v2
      with:
        repository: KWHYTHUB/suite
        path: suite
        ref: nightly
        submodules: recursive
        token: '${{ secrets.SAPPHIRE_BOT_PUSH_BIN_TOKEN }}'

    - name: Download Windows artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.SAPPHIRE_BOT_PUSH_BIN_TOKEN}}
        workflow: build.yml
        workflow_conclusion: success
        name: Windows Binary
        path: '${{ github.workspace }}/windows'
        
    - name: Download MacOS artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.SAPPHIRE_BOT_PUSH_BIN_TOKEN}}
        workflow: build.yml
        workflow_conclusion: success
        name: macOS Binary
        path: '${{ github.workspace }}/macos'
      
    - name: Move files to suite
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cp -r ./windows/* ./suite/windows
        cp -r ./macos/* ./suite/macos
        
    - name: Commit and push to suite
      working-directory: ${{ github.workspace }}/suite
      run: |
        git config --local user.email "${{ secrets.SAPPHIRE_BOT_EMAIL }}"
        git config --local user.name "SapphireBot"
        git add -A
        git commit -m "Loader update from ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
        git push "https://SapphireBot:${{ secrets.SAPPHIRE_BOT_PUSH_BIN_TOKEN}}@github.com/KWHYTHUB/suite.git"
